# Generated by Django 2.1.7 on 2019-05-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pca',
            fields=[
                ('pca_1', models.FloatField(blank=True, db_column='PCA_1', null=True)),
                ('pca_2', models.FloatField(blank=True, db_column='PCA_2', null=True)),
                ('pca_3', models.FloatField(blank=True, db_column='PCA_3', null=True)),
                ('class_field', models.TextField(blank=True, db_column='class', null=True)),
                ('index', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PCA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tsne',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('tsne_1', models.FloatField(blank=True, db_column='tSNE_1', null=True)),
                ('tsne_2', models.FloatField(blank=True, db_column='tSNE_2', null=True)),
                ('tsne_3', models.FloatField(blank=True, db_column='tSNE_3', null=True)),
                ('class_field', models.TextField(blank=True, db_column='class', null=True)),
            ],
            options={
                'db_table': 'tSNE',
                'managed': False,
            },
        ),
    ]
